import BannerItemType from "@/types/bannerType";

export const bannerItems: BannerItemType[] = [
	{
		label: "NEW",
		title: "Продам велосипед",
		condition: "нове",
		price: "23 333 грн",
		buttonName: "Купити",
		backgroundImage: "/images/main-banners/banner_bicycle.jpg",
		// backgroundImages: {
		// 	mobile1x: "/images/banners/banner_bicycle_mob@1x.jpg",
		// 	mobile2x: "/images/banners/banner_bicycle_mob@2x.jpg",
		// 	laptop1x: "/images/banners/banner_bicycle_desk@1x.jpg",
		// 	laptop2x: "/images/banners/banner_bicycle_desk@2x.jpg",
		// },
		url: "/announcement?id=153",
	},
	{
		label: "SALE",
		title: "Аксесуари для мобільних телефонів",
		condition: "нове",
		price: "від 300 грн",
		buttonName: "Купити",
		backgroundImage: "/images/main-banners/banner_chehly.jpg",
		// backgroundImages: {
		// 	mobile1x: "/images/banners/banner_plates_mob@1x.jpg",
		// 	mobile2x: "/images/banners/banner_plates_mob@2x.jpg",
		// 	laptop1x: "/images/banners/banner_plates_desk@1x.jpg",
		// 	laptop2x: "/images/banners/banner_plates_desk@2x.jpg",
		// },
		url: "/seller/271",
	},
	{
		label: "NEW",
		title: "Новинки в одязі та взутті",
		condition: "нове",
		price: "від 150 грн",
		buttonName: "Перейти",
		backgroundImage: "/images/main-banners/banner_moda.jpg",
		// backgroundImages: {
		// 	mobile1x: "/images/banners/banner_clothes_mob@1x.jpg",
		// 	mobile2x: "/images/banners/banner_clothes_mob@2x.jpg",
		// 	laptop1x: "/images/banners/banner_clothes_desk@1x.jpg",
		// 	laptop2x: "/images/banners/banner_clothes_desk@2x.jpg",
		// },
		url: "catalogy?categoryId=1&productType=NEW",
	},
	{
		label: "INFO",
		title: "Куплю автомобіль",
		condition: "вживане",
		price: "від 500 000 грн",
		buttonName: "Запропонувати",
		backgroundImage: "/images/main-banners/banner_car.jpg",
		// backgroundImages: {
		// 	mobile1x: "/images/banners/banner_photo_mob@1x.jpg",
		// 	mobile2x: "/images/banners/banner_photo_mob@2x.jpg",
		// 	laptop1x: "/images/banners/banner_photo_desk@1x.jpg",
		// 	laptop2x: "/images/banners/banner_photo_desk@2x.jpg",
		// },
		url: "/catalogy?categoryId=4&topSubCategoryId=34&section=BUY",
	},
	{
		label: "SALE",
		title: "Будинки вашої мрії",
		condition: "вживане",
		price: "від 100 тис. грн",
		buttonName: "Перейти",
		backgroundImage: "/images/main-banners/banner_house.jpg",
		// backgroundImages: {
		// 	mobile1x: "/images/banners/banner_chair_mob@1x.jpg",
		// 	mobile2x: "/images/banners/banner_chair_mob@2x.jpg",
		// 	laptop1x: "/images/banners/banner_chair_desk@1x.jpg",
		// 	laptop2x: "/images/banners/banner_chair_desk@2x.jpg",
		// },
		url: "/catalogy?categoryId=7",
	},
];
