export type FormValues = {
  // topSubCategoryId: number | null;
  // lowSubCategoryId: number | null;
  // categoryId: number | null;
  // section: "buy" | "sell" | "";
  // cityId: number | null;
  // productType: string;
  // price: number | "";
  // title: string;
  // description: string;
  // deliveryMethods: string[];
  topSubCategoryId: number | null;
  lowSubCategoryId: number | null;
  categoryId: number | null;
  section: string;
  cityId: number | null;
  productType: string;
  price: string;
  isNegotiable: boolean;
  title: string;
  description: string;
  deliveryMethods: string[];
  product: string;
  category: string;
  subcategory: string;
  location: string;
  condition: string;
  delivery: string;
  
};
